### ISSUE TITLE
Weapon list not up to date

### ISSUE THREAD

**Issue by tulpia** [LartTyler/MHWDB-API#117]
Hello !
First of all, great job with the API ! I've been using it for a personal project and it's really easy to use and consume.

I've noticed that the Kulve Taroth weapons are missing. I'm currently making a builder with your API and the KT weapons like the Kjaar or the Taroth Glutton HBG are really important and part of the current MHW meta (pre-Iceborne atleast) and they're missing from the weapons API. Could you add them, if it's not too much to ask ? Thanks !

**Comment by Kiszaner** [comment]
I can pick this up, I will add those weapons into the DB as soon as possible. I will add more weapons from KV later.
I will keep you posted in this issue.

**Comment by tulpia** [comment]
Thanks alot @Kiszaner  !

**Comment by Kiszaner** [comment]
You are welcome!

I already added yesterday Taroth Glutton HBG data and all KV HBG rank 6, so check if it works as expected and let me know.
I saw also that there are quite a lot of KV weapons, so it will take some time to have them all in the DB :sweat_smile:

**Comment by DeveloperPaul123** [comment]
@Kiszaner I would suggest first adding the "meta" KT weapons. I would argue it's almost not necessary to add _all_ the KT weapons as many of them are never used.

**Comment by Kiszaner** [comment]
Sure, could you please share the list of curent KT meta weapons? That would speed up the process a lot

**Comment by tulpia** [comment]
@Kiszaner https://www.reddit.com/r/MonsterHunterWorld/comments/akdirc/all_viable_kulve_taroth_weapons/

https://www.reddit.com/r/MonsterHunterMeta/comments/arycmn/kulve_at_kulve_best_weapon_list/egrwc6n?utm_source=share&utm_medium=web2x
https://www.reddit.com/r/MonsterHunterMeta/comments/arycmn/kulve_at_kulve_best_weapon_list/egrwivz?utm_source=share&utm_medium=web2x

**Comment by Kiszaner** [comment]
I'm following the first link and I already added LBG, HBG, longswords and dual blades, let me know if the values are as expected, specially sharpness values (I'm taking those from Kiranico)

**Comment by LartTyler** [comment]
@Kiszaner How'd you get the sharpness values you used from Kiranico? I went to go spot check some of the weapons, and they look slightly off. For example, the MHWG page for [Taroth Sword "Fire"](http://mhwg.org/ida/233196.html) lists the base white sharpness as 40, but the [sword in the API](https://contrib.mhw-db.com/objects/weapons/long-sword/1282) shows a base sharpness of 50. In the past, we've favored sharpness values from MHWG as more accurate, but I just wanted to check that I wasn't missing some information before going in and changing the stuff you added.

**Comment by Kiszaner** [comment]
@LartTyler I'm getting the values inspecting Kiranico's web source code, as in each blade info there is a sharpness gauge representation with some widths/percentages for each color. Knowing that a total sum of 100 in those percentages equals to 400 in sharpness value, I can calculate which value should I assign to each color in the DB. This method works as I double checked it on other sources, but in Kiranico data is more condensed to DB relevant fields and it's easier to get it from.
This specific case seems to be my bad typing the values (I started doing them 1 handcraft at a time before knowing about set all functionality 😅), which I will fix right away.

As an example of how the methods works, you can see in this screenshot the code to represent Taroth Sword "Fire" handcraft+5 sharpness in Kiranico. 
White value is set with a width of 22,5px. This means that white bar is a 22,5% of a total of 400 sharpness (as all widths sum 100), which corresponds to a value of 90.
![image](https://user-images.githubusercontent.com/9079893/71269839-85f4f300-2350-11ea-9819-b925665a905b.png)

**Comment by LartTyler** [comment]
Got it, that makes sense. Were you able to go back and fix those incorrect values? If not, I'm happy to hop in and start working through those.

**Comment by LartTyler** [comment]
Since it looks like the sharpness values were corrected and the weapon list appears to be complete, I'm going to close this. If there are any other weapons missing, please open a new issue!
