### ISSUE TITLE
Empty field when query items with "+" in the item name

### ISSUE THREAD

**Issue by sziyan** [LartTyler/MHWDB-API#124]
Firstly, wonderful project. Kudos to your hard work.

When I tried to query the api with this: [Monster Bone +](https://mhw-db.com/items/?q={%22name%22:%22Monster%20Bone+%22}),  there are no results returned from the api.

However, I am able to query by id: [Monster Bone + ID](https://mhw-db.com/items/150), so the data does exist in the database.

Is the api query unable to search when there's a "+" in the search terms? 

Thanks

**Comment by LartTyler** [comment]
My guess is that you're not URI encoding the `+` sign in your query. It should look [something like this](https://mhw-db.com/items/?q=%7B%22name%22:%22Monster%20Bone%2B%22%7D).
