### ISSUE TITLE
Events in Contribution Site Not Up to Date

### ISSUE THREAD

**Issue by DeveloperPaul123** [LartTyler/MHWDB-API#136]
I'm not sure if this is an issue with the contrib site itself or the API, but no Iceborne events are showing up under the `Events` section.

**Comment by LartTyler** [comment]
This should be resolved with [v1.17.3](https://github.com/LartTyler/MHWDB-API/releases/tag/1.17.3).

**Comment by DeveloperPaul123** [comment]
Things seems to be working properly, thanks for the quick fix!
