### ISSUE TITLE
[Question] How to query for all armors with X set of skills

### ISSUE THREAD

**Issue by pbalzano91** [LartTyler/MHWDB-API#163]
Let's say I want to grab all armor pieces (from /armor endpoint) which contain a set of skills.

How can I achieve that? [$all](https://docs.mongodb.com/manual/reference/operator/query/all/) mongo operator over "skills.skillName" would suffice but it's not available.

Thanks!

**Comment by pbalzano91** [comment]
@LartTyler any insight on this?

**Comment by LartTyler** [comment]
Sorry for the slow response. Unfortunately, that isn't gonna be doable with API queries alone. What you'll probably want to do is something like this:

```
https://mhw-db.com/armor?q={"skills":{"$size":{"$gte":2}},"skills.skill":{"$in":[1,2]}}
```

That'll return any armor with at _least_ two skills attached to it, and that also has one or both of skills with ID 1 and 2. Then you'd need to filter the results down in your application to only those that have both the skills you're looking for.

EDIT: Fixed a type in URL.

**Comment by pbalzano91** [comment]
Awesome, I’ll give that a try. Thank you very much for your answer and thank you for this great API 🙂. Keep it up!
