### ISSUE TITLE
Add resource for attacks

### ISSUE THREAD

**Issue by stocky37** [LartTyler/MHWDB-API#52]
Off the top of my head, something like the following would be useful:
```
{
      "id": "double-slash",
      "name": "Double Slash",
      "damageType": "severing",
      "motionValues": [8, 10],
      "weaponType": "dual-blades"
}
```

**Comment by LartTyler** [comment]
That's a good idea. It looks like they're on Kiranico ([here, for example](https://mhworld.kiranico.com/guide/dual-blades#motion-values)), so I should be able to source it from there. I'll add it to the backlog, thanks!

**Comment by LartTyler** [comment]
Before I get started on this, I noticed that some weapons have different motion values depending on their current sharpness (e.g. the ["Spirit Helm Breaker" move on long swords](https://mhworld.kiranico.com/guide/long-sword#motion-values)). What do you think would be the best way to represent that in the API?

**Comment by LartTyler** [comment]
So here's what I've got so far.

```json
[
  {
    "id": 83,
    "name": "Double Slash",
    "weaponType": "dual-blades",
    "damageType": "sever",
    "stun": null,
    "exhaust": null,
    "values": [
      8,
      10
    ]
  },
  {
    "id": 84,
    "name": "Double Slash Return Stroke",
    "weaponType": "dual-blades",
    "damageType": "sever",
    "stun": null,
    "exhaust": null,
    "values": [
      9,
      10
    ]
  },
  {
    "id": 85,
    "name": "Circle Slash",
    "weaponType": "dual-blades",
    "damageType": "sever",
    "stun": null,
    "exhaust": null,
    "values": [
      11,
      9,
      11
    ]
  }
]
```

Pretty much exactly what you used as an example in your original post, but with stun and exhaust potencies (when applicable). For the two issues I brought up earlier today, I decided to 1) list gauge based motion values separately (i.e. "Spirit Helm Breaker (White)" and "Spirit Helm Breaker (Yellow)" are two separate entities in the API, despite having identical values) and 2) list the maximum possible number of hits for moves that can hit up to a certain number of times.

**Comment by stocky37** [comment]
I was literally just taking a look now at Spirit Helm Breaker and was thinking exactly what you've ended up with. I think it makes sense as an array of all possible hits since with every multi-move combo different hits could hit or miss so it could be argues that all the motion values are already *optional*.

**Comment by LartTyler** [comment]
This has been added with the release of [v1.11.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.11.0).
