### ISSUE TITLE
How to query for all weapon "final forms"?

### ISSUE THREAD

**Issue by stocky37** [LartTyler/MHWDB-API#53]
I was thinking of checking for anything with an empty "crafting.branches" array. Would that make sense?

In any case, I can't get any queries on the crafting field to work, I keep getting the following error:

```
{"error":{"code":"search.error","message":"An error occurred while running your search: Unknown field: crafting"}}
```

with a simple query, like so:
```
https://mhw-db.com/weapons?q={"crafting": {"$exists": true}}
```

Any ideas?

**Comment by LartTyler** [comment]
The API should properly convert object checks (like what you're doing) to the right path, but it's possible something got messed up in a previous update that I missed. For the time being, you can do something like this:

```
https://mhw-db.com/weapons?q={"crafting.id":{"$exists":true}}
```

In the morning, I'll take a look at it and get that fixed so you won't need to worry about a workaround.

**Comment by LartTyler** [comment]
This should be resolved now. Feel free to continue using the `crafting.id` field name, but queries against just `crafting` should work properly now.

**Comment by stocky37** [comment]
Looks like queries are working fine with the `crafting` field now. Now I'm just struggling to figure out a way to actually query that the branches array is empty. So far I've tried the following queries to no avail:

```json
{"crafting.branches": {"$size": 0}}
```
Doesn't work since `dbstudios/doctrine-query-document` has not implemented the `$size` operator

```json
{"crafting.branches": {"$exists": true}}
```
Obviously finds all weapons since branches exists since it's defined as an empty array.

Any ideas?

**Comment by LartTyler** [comment]
I was actually thinking about that earlier today, while I was fixing the field resolution error you were encountering initially. You're right, the library doesn't have an implementation of `$size`, nor does it support anything that'd allow you to find objects whose `crafting.branches` field is empty.

Tomorrow morning, I'll see what I can do to make your initial example of `{"crafting.branches":{"$size":0}}` work. I'll reopen this issue, and update you on here once I have a resolution for you.

**Comment by LartTyler** [comment]
@stocky37 This was a fun one to resolve. Instead of adding a `$size` operator to the library, I ended up making it possible to simply append `.length` to any field that's an array of related objects. So, to achieve what you were trying to do, you would use [/weapons?q={"crafting.branches.length": 0}](https://mhw-db.com/weapons?q={"crafting.branches.length":0}).

As I mentioned, this will work for ANY array of objects in the API, not just `Weapon.crafting.branches`. I should have the docs updated soon to reflect that. Lemme know if you have any issues making this work!

**Comment by stocky37** [comment]
Awesome, that sounds like a neat workaround. Thanks a lot!
