### ISSUE TITLE
Skill Carving Master is missing

### ISSUE THREAD

**Issue by TanukiSharp** [LartTyler/MHWDB-API#61]
The skill `Carving Master` is missing from the the `/skills` API.
This skill is an armor set skill and is bestowed by the `Commision` armor, available once one get a `Research Commision Ticket`. Here is the info how to obtain this ticket: https://monsterhunterworld.wiki.fextralife.com/Research+Commission+Ticket

The skill activates with 4 armor pieces.

**Comment by LartTyler** [comment]
Hmm.. Yeah, it's definitely not there, not even under a different name or a misspelling. The skill list is pulled from Kiranico, and it looks like Carving Master isn't on there either. Thanks for pointing this out!

**Comment by stocky37** [comment]
On a similar note, the affinity value for the fire and ice dual blades is also missing. Looks like a similar problem where Kiranico have it wrong on there.

**Comment by LartTyler** [comment]
Gotcha, I'll get that updated as well.

**Comment by LartTyler** [comment]
This should (finally!) be resolved in [v1.13.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.13.0).
