### ISSUE TITLE
Invalid CORS header response

### ISSUE THREAD

**Issue by stocky37** [LartTyler/MHWDB-API#63]
I can no longer access the api through front-end web applications. The response appears to have an invalid `Access-Control-Allow-Origin` header. The error in Chrome is:
```
Failed to load https://mhw-db.com/skills: The 'Access-Control-Allow-Origin' header contains the invalid value ''
```

It looks like the header is empty. Pretty sure it's also supposed to contain a wildcard as the rest of the CORS headers have one:
```
access-control-allow-credentials: false
access-control-allow-headers: *
access-control-allow-methods: *
access-control-allow-origin: 
```

**Comment by LartTyler** [comment]
Thanks for letting me know. I'm looking into it now, I'll let you know when it's resolved.

**Comment by LartTyler** [comment]
@stocky37 It should be working now. Can you confirm that things are fixed on your end as well? Please clear your cache before doing so, just to be safe.

**Comment by stocky37** [comment]
@LartTyler it's all good for those endpoints but now it's happening again for `/motion-values`

**Comment by LartTyler** [comment]
@stocky37 Sorry for the slow response. I'm not seeing this happening on my end. Can you confirm that you're still having this issue?

**Comment by stocky37** [comment]
All good it looks fine from here now too.
