### ISSUE TITLE
Fix large amounts of incorrect information being pulled from Kiranico

### ISSUE THREAD

**Issue by LartTyler** [LartTyler/MHWDB-API#65]
**Taken from @TanukiSharp's analysis of API data in #51.**

---

**GreatSword**

Buster Blade 3 (id: 6)
- slot should be '1--' but is '---'

Jagras Hacker 1 (id: 23)
- element 1 should be '(Water 210)' but is '(Ice 210)'

Jagras Hacker 2 (id: 24)
- element 1 should be '(Water 240)' but is '(Ice 240)'

Jagras Hacker 3 (id: 25)
- element 1 should be '(Water 300)' but is '(Ice 300)'

Gnashing Flammenzahn (id: 56)
- element 1 should be 'Fire 480' but is 'Fire 360'

Daora's Decimator (id: 85)
- affinity should be 10 but is 0

Wyvern Ignition "Impact" (id: 1181)
- element 1 should be '(Fire 510)' but is '(Fire 240)'

Missing weapon ガイラブレイズ・水
Missing weapon ガイラブレイズ・氷
Missing weapon ガイラブレイズ・睡眠

---

**LongSword**

Brazenridge 2 (id: 111)
- defense should be 30 but is 25

Missing weapon: Azure Star "Dragon Dance"
- rarity: 7
- attack: 495
- affinity: 30%
- defense: 0
- element: 'Water 180'
- slots: '3--'
- craft: ?
- cost: ?
- augmentation slots: 2

Missing weapon ガイラソード・水
Missing weapon ガイラソード・毒
Missing weapon ガイラソード・麻痺

---

**SwordAndShield**

Lumu Tabar 3 (id: 205)
- slot should be '31-' but is '21-'

Grand Barong 2 (id: 224)
- defense should be 10 but is 0

Carapace Edge 1 (id: 241)
- affinity should be -10 but is 0

Carapace Edge 2 (id: 242)
- affinity should be -10 but is 0

Carapace Edge 3 (id: 243)
- affinity should be -10 but is 0

Barroth Club 3 (id: 246)
- slot should be '21-' but is '11-'

Missing weapon ガイラスライサー・水
Missing weapon ガイラスライサー・龍
Missing weapon ガイラスライサー・爆破

---

**DualBlades**

Freeze Daggers 2 (id: 280)
- element 1 should be 'Ice 90' but is 'Ice 60'

Diablos Clubs 2 (id: 308)
- defense should be 15 but is 10

Dragonbone Twinblades 2 (id: 333)
- element 1 should be 'Dragon 150' but is 'Dragon 120'

Twin Nails (id: 342)
- affinity should be 10 but is 0

Fire and Ice (id: 343)
- affinity should be 10 but is 0

Xeno Raqs (id: 344)
- affinity should be 15 but is 0

Missing weapon ガイラダガー・水
Missing weapon ガイラダガー・氷
Missing weapon ガイラダガー・毒

---

**Hammer**

Lightning Bash 1 (id: 376)
- element 1 should be 'Thunder 240' but is 'Thunder 832'

Diablos Sledge 2 (id: 403)
- element 1 should be '(Ice 150)' but is '(Ice 120)'

Anja Striker 3 (id: 416)
- element 1 should be 'Fire 450' but is 'Fire 390'

Dragonbone Basher 3 (id: 419)
- slot should be '1--' but is '---'

Icesteel Hammer (id: 424)
- affinity should be 10 but is 0

Daora's Colossus (id: 425)
- affinity should be 10 but is 0

Xeno Maph'agarna (id: 426)
- affinity should be 15 but is 10

Devil's Due (id: 1158)
- slot should be '---' but is '3--'

Devil's Crush (id: 1159)
- slot should be '---' but is '3--'

Missing weapon ガイラハンマー・水
Missing weapon ガイラハンマー・雷
Missing weapon ガイラハンマー・氷

---

**HuntingHorn**

Gama Horn 1 (id: 472)
- slot should be '22-' but is '2--'

Gama Horn 2 (id: 473)
- slot should be '22-' but is '2--'

Lumu Barone 1 (id: 487)
- element 1 should be '(Water 420)' but is 'Water 420'

Lumu Barone 2 (id: 488)
- element 1 should be '(Water 480)' but is 'Water 480'

Lumu Barone 3 (id: 489)
- element 1 should be '(Water 570)' but is 'Water 570'

Missing weapon ガイラバイプ・水
Missing weapon ガイラバイプ・龍
Missing weapon ガイラパイプ・麻痺

---

**Lance**

Blue Tail (id: 550)
- element 1 should be 'Fire 270' but is 'Fire 210'

Garon Lance 2 (id: 574)
- affinity should be 15 but is 0

Dragonbone Lance 3 (id: 585)
- slot should be '11-' but is '1--'

Thunderpike (id: 588)
- affinity should be 10 but is 0

Missing weapon ガイラクレスト・水
Missing weapon ガイラクレスト・雷
Missing weapon ガイラクレスト・睡眠
Missing weapon ガイラクレスト・惨爪

---

**Gunlance**

Steel Gunlance 3 (id: 603)
- has no element but should be '(Blast 210)'

Jyura Buster 1 (id: 626)
- slot should be '1--' but is '---'

Jyura Buster 2 (id: 627)
- slot should be '1--' but is '---'

Jyura Buster 3 (id: 628)
- slot should be '1--' but is '---'

Missing weapon ガイラバスター・水
Missing weapon ガイラバスター・毒
Missing weapon ガイラバスター・睡眠
Missing weapon ガイラバスター・王

---

**SwitchAxe**

Power Smasher 1 (id: 716)
- elderseal should be Average but is None

Power Smasher 2 (id: 717)
- slot should be '3--' but is '---'
- elderseal should be Average but is None

Dragonbone Slicer 1 (id: 745)
- elderseal should be Low but is Average

Dragonbone Slicer 2 (id: 746)
- elderseal should be Low but is Average

Dragonbone Slicer 3 (id: 747)
- elderseal should be Low but is Average

Xeno Martshu (id: 755)
- affinity should be 15 but is 0

Missing weapon ガイラアックス・雷
Missing weapon ガイラアックス・睡眠
Missing weapon ガイラアックス・麻痺
Missing weapon ガイラアックス・角

---

**ChargeBlade**

Hard Bone Strongarm 3 (id: 789)
- slot should be '1--' but is '---'

Missing weapon: Dante's Devil Sword
- rarity: 8
- attack: 720
- affinity: 0%
- defense: 0
- element: 'Thunder 150'
- slots: '11-'
- phial type: Impact
- craft: Red Orb x2, Anjanath Gem x1, Odogaron Gem x1, Teostra Mane x4
- cost: 24000z
- augmentation slots: 1

Missing weapon ガイラアームズ・雷
Missing weapon ガイラアームズ・氷
Missing weapon ガイラアームズ・睡眠
Missing weapon ガイラアームズ・角

---

**InsectGlaive**

Nergal Reaper (id: 839)
- elderseal should be High but is None

Catastrophe's Light (id: 840)
- elderseal should be High but is None

Datura Blade 1 (id: 863)
- slot should be '11-' but is '---'

Hazak Entoma 1 (id: 876)
- elderseal should be Average but is None

Hazak Entoma 2 (id: 877)
- elderseal should be Average but is None

Garon Rod 2 (id: 898)
- slot should be '1--' but is '---'

Dragonbone Glaive 1 (id: 901)
- elderseal should be Low but is None

Dragonbone Glaive 2 (id: 902)
- elderseal should be Low but is None

Dragonbone Glaive 3 (id: 903)
- elderseal should be Low but is None

Blacksteel Glaive 1 (id: 907)
- elderseal should be Low but is None

Blacksteel Glaive 2 (id: 908)
- elderseal should be Low but is None

Xeno Shmaena (id: 911)
- elderseal should be Low but is None

Bad Wing (id: 1170)
- elderseal should be High but is None

Grunge Storm (id: 1171)
- elderseal should be High but is None

Missing weapon ガイラブレード・水
Missing weapon ガイラブレード・氷
Missing weapon ガイラブレード・麻痺

**Comment by TanukiSharp** [comment]
The source is `mhwg.org`, not `kiranico`.

**Comment by LartTyler** [comment]
This is resolved in [v1.13.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.13.0).
