### ISSUE TITLE
Image permission error from weapons 

### ISSUE THREAD

**Issue by Dazorn96** [LartTyler/MHWDB-API#67]
A lot of images (**assets.image**) from _weapons objects_ return **403 Permission Denied** error.
Thanks :)

**Comment by LartTyler** [comment]
I checked a few, and wasn't able to recreate the issue you're having. Can you send me API links for a few weapons that you've noticed this happening for?

**Comment by Dazorn96** [comment]
This is the error i am getting:
![image](https://user-images.githubusercontent.com/10536581/42949116-571c4b14-8b71-11e8-806a-d5bd291108e8.png)
Example: https://assets.mhw-db.com/weapons/great-sword/ef4937214b610b35b945bc4906f96181c600d0b0.1b059957e9d5f1a76227303d5ce7e5ae.png
