### ISSUE TITLE
Armor images are not accessible.

### ISSUE THREAD

**Issue by yoonhok524** [LartTyler/MHWDB-API#76]
Here is the "Leather Helm"'s image.
When I call it, "Access Deny" message is shown.

https://assets.mhw-db.com/armor/0c3c7586ed8b763a29b0fb6cb1b11518.e5f105b7b926b37b9deb7261b9b5429618850e33.png

**Comment by LartTyler** [comment]
Thanks for the heads up. I'll take a look, and let you know once this is resolved.

**Comment by LartTyler** [comment]
So... it looks like when I changed data sources for 1.13.0, I failed to port over the image scraping code that was present in the armor scraper I built for Kiranico. I'm going to get started on building out a replacement, but it's not likely that it'll be done until later tonight, after I get off work. Sorry for the inconvenience, I'll keep you posted.

**Comment by LartTyler** [comment]
This has been resolved in [v1.13.1](https://github.com/LartTyler/MHWDB-API/releases/tag/1.13.1).
