### ISSUE TITLE
Missing sharpness values

### ISSUE THREAD

**Issue by LartTyler** [LartTyler/MHWDB-API#81]
Both of the following weapons have no durability values (reported by @TanukiSharp):

- [Azure Star "Dragon Dance"](https://mhw-db.com/weapons?q={%22name%22:%22Azure%20Star%20\\%22Dragon%20Dance\\%22%22})
- [Sapphire Star Lance](https://mhw-db.com/weapons?q={%22name%22:%22Sapphire%20Star%20Lance%22})

**Comment by TanukiSharp** [comment]
Thanks for filling the issue for me ;)

**Comment by LartTyler** [comment]
After way too long, these have finally been fixed.
