### ISSUE TITLE
deviation/shellingType value discrepancies

### ISSUE THREAD

**Issue by todc** [LartTyler/MHWDB-API#83]
Hi again,

I noticed a few inconsistencies with some of the weapon data. They're not a big deal, but for the sake of consistency, it may be worth correcting.

ID: 1025
attributes.deviation = "Average" instead of "average"

ID: 1173
attributes.deviation = "High" instead of "high"

ID: 673
attributes.shellingType = "Normal LV2" instead of "Normal Lv2"

**Comment by LartTyler** [comment]
Those three weapons have been corrected. With the new contribution system live, I'm gonna be going through all the objects in the API to look for other inconsistencies like this. Sorry for the delayed response, and thank you for bringing this to my attention!
