### ISSUE TITLE
Armor list not updated

### ISSUE THREAD

**Issue by robertomarinas** [LartTyler/MHWDB-API#85]
Hi! First off, I would like to say good job on doing this API service! I'm currently building a hunter-helper, mobile-first web app, using your API. I'm currently focusing on building an Armor Loadout generator and having an updated resource is paramount. I tested the fetch armor endpoint and I can see that the latest armors are missing (Gamma Sets, Behemoth, etc..).

I know that this is a solo project of yours and you have other important things to do. I'm just asking if you could update the resource when you have the time,

Again, good job on this! I've been playing monster hunter since psp days and the project that I'm working on is a passion project of mine. Keep up the good work!

**Comment by LartTyler** [comment]
Hey! Glad you're enjoying the API. I'm aware of several resources being out of date (missing armor being one of them). The project originally relied on scraped data from Kiranico, which hasn't updated in a while. I'm currently working on getting away from relying on scraped data to populate the API, and once that's done I plan on going through everything and double checking that nothing is missing or incorrect.

If you'd like to help with checking the presence and validity of data (even if it's just the armor data that's relevant to your project), let me know. My plan is to make it possible for anyone to submit changes to specific objects in the API, and I'd be happy to send a registration link your way once it's ready to be used. If not, I'll be sure to update this issue once I've had a chance to go over the armor data myself.

**Comment by robertomarinas** [comment]
I'd be happy to help! Let me know once you've setup everything.

**Comment by vyong1** [comment]
Hey, I'm willing to help too. I'm working on an app of my own and updated data would be great.

**Comment by LartTyler** [comment]
It is! I haven't had as much time to work on it lately as I'd like, but I'm working on wrapping up a [contribution system](https://github.com/LartTyler/MHWDB-Contrib) to make it easier to manage data in the API. If you'd like to help with the contribution system itself, it would be much appreciated it. If you're interested in helping with data management once the contrib system is up, that's cool too, and I'd be happy to send an invite your way once it's live.

**Comment by LartTyler** [comment]
@robertomarinas @vyong1  If either of you are still interested in helping with the contribution stuff I mentioned, feel free to send an email to tyler@lartonoix.com so I can send an invite your way. I plan on rolling out the contribution system over the next couple of days, and any help with getting the API up to date would be greatly appreciated!

**Comment by mingjunlu** [comment]
@LartTyler I would like to help with the data as well! I've just sent you an email 🙂

**Comment by mingjunlu** [comment]
**Master Rank Armors are up-to-date!** (Rajang's included)

Currently max defense values and required crafting materials are left empty because it will take a lot of time and effort to update. Also, please keep in mind that there may be human-errors such as typos since those data are manually entered.

Anyway, enjoy hunting and building things!

**Comment by LartTyler** [comment]
@mingjunlu Awesome, I appreciate all your help :) I glanced over some of the additions, and it all looks good, but I'll set aside some time to give it a more detailed once-over.

**Comment by pierretusseau** [comment]
Hello guys !

So, building a webapp based on this API I found some misplaced armor-type items, here is the list

### Low rank
**153** : Kirin Leg Guards => Shoudl be legs not gloves
### High rank
**602** : Kirin Leg Guards Alpha => Should be legs not gloves
**607** : Kirin Leg Guards Beta => Should be legs not gloves
**700** : Vaal Hazak Mail Gamma => Should be chest not head
**726** : Xeno'jiiva Claws Gamma => Should be gloves not head
### Master Rank
**1058** : Ruinous Coil Beta + => Should be waist not chest
**1197** : Esurient Vambraces Beta + => Should be gloves not chest
**1219** : Damascus Greaves Beta + => Should be legs not waist

Is a quick fix possible ?

**Comment by mingjunlu** [comment]
@pierretusseau All fixed. Thanks for reporting this!

**Comment by DeveloperPaul123** [comment]
@pierretusseau Is your web app available yet?

**Comment by pierretusseau** [comment]
@DeveloperPaul123 not yet, we're working on the CI/CD for a public distribution soonTM ;) ;)

Is there any known project using the API already ? I'm really curious

**Comment by DeveloperPaul123** [comment]
Sounds good, looking forward to seeing it.

I'm not sure of a list of projects using this api. I'm definitely tempted to make an android app using this api though.

**Comment by pierretusseau** [comment]
I've seen you forked MHWorldDatabase, which is pretty cool btw. We focus mainly on Desktop browser right know. I'm kinda tired of HoneyHunter builder, which is cool but really old fashioned, and wish to build something in React. Feel free to visit the repo of tulpia if you wish :)
(probbly not the best place to talk about this, but I don't know where I could discuss this)

**Comment by DeveloperPaul123** [comment]
>which is pretty cool btw

Thanks @pierretusseau!

Yeah I personally use Athena's armor set search and MHArmory to do set searching. I like this API however because if you build something arounnd it, it can easily be updated in the future without necessarily requiring that your web/mobile/desktop app be updated necessarily. 

I'm sorry, but I'm not sure what you mean by "repo of tulpia", I couldn't find a repo on Github with that name.

**Comment by pierretusseau** [comment]
@DeveloperPaul123 oh I didn't know there was a windows application for it, nice insight.

I was talking about https://github.com/tulpia/fieldguide (wip obviously)

**Comment by DeveloperPaul123** [comment]
Yeah the windows apps are quite good actually for finding armor sets. 

Nice, I'll keep an eye on that project.

**Comment by DeveloperPaul123** [comment]
I've also added all the armor from the event quests that just dropped. Only thing missing are the fully upgraded defense levels for them. 

@LartTyler Is there anything else missing? Or can this issue be closed?

**Comment by LartTyler** [comment]
So I tried pulling a list of armor from Fextralife and comparing it against what's in the API, but I'm noticing a ton of errors on Fextralife (things like "Anja Vambraces Alpha +" being named "Anjanath Vambraces Alpha +" _and_ "Anja Vambraces +") that's making it impossible to quickly compare the lists. I think for now, it's safe to close the issue. We can always open a new one if we find armor that's missing.
