### ISSUE TITLE
Missing ElementType Stun

### ISSUE THREAD

**Issue by Kiszaner** [LartTyler/MHWDB-API#94]
I think the DB is missing an `ElementType`: stun. It appears in the DB as an `Ailment`, but I think it also should be an `ElementType`. It is the same case as `sleep` and `poison`.

**Comment by LartTyler** [comment]
I know that some weapons can have paralysis as an element type, but are there any weapons that directly deal stun damage? I know that blunt damage can stun, for example, but as far as I'm aware, there aren't any weapons with stun as their element, at least not in the same way that a weapon might deal blast, sleep or paralysis damage.

**Comment by Kiszaner** [comment]
I agree, maybe it's not an element type by itself, but the thing is that monsters have their own entry in the weaknesses table for stun. These entries are all element types, but currently the DB doesn’t reflect stun weakness at all, so that was the reason why I was considering stun like a sort of element type.
<img width="201" alt="Lavasioth ailments" src="https://user-images.githubusercontent.com/9079893/60902932-bd735580-a270-11e9-8424-d7a1d464e844.png">

**Comment by LartTyler** [comment]
Gotcha, that makes sense. I agree, at the very least, it should appear as an option for weaknesses.

**Comment by LartTyler** [comment]
This is resolved with [v1.15.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.15.0) of the API and [v1.2.0](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.2.0) of the contrib system.
