### ISSUE TITLE
Missing species from The Witcher collaboration

### ISSUE THREAD

**Issue by Kiszaner** [LartTyler/MHWDB-API#95]
In February 2019 Capcom did a collaboration with The Witcher III including a new species in the game. Should this species (and the corresponding monsters) be in the DB? I think the missions from the event are not longer playable, so I'm not sure if it "deserves" to be included.
Notice that without this species, monsters from that collaboration can't be included in the DB.

**Comment by LartTyler** [comment]
Yeah, for the sake of completeness, it would be good to support the collab monsters.

**Comment by LartTyler** [comment]
[This page](https://monsterhunterworld.wiki.fextralife.com/Leshen) labels the species as "Relict," do you know if that's accurate? I didn't participate in the Witcher collab at all, so I'm not sure.

**Comment by Kiszaner** [comment]
I didn’t play the collab, but that information seems accurate as in [The Witcher Wiki](https://witcher.fandom.com/wiki/Leshy#The_Witcher_3:_Wild_Hunt) the monster is under the same species name.

**Comment by LartTyler** [comment]
Sounds good. The MHW Wikia page confirms it as well, so that's what I'm gonna go with.

**Comment by LartTyler** [comment]
This is resolved with [v1.15.0](https://github.com/LartTyler/MHWDB-API/releases/tag/1.15.0) of the API and [v1.2.0](https://github.com/LartTyler/MHWDB-Contrib/releases/tag/1.2.0) of the contrib system.
